GP12_Planner:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.025
  kinematics_solver_attempts: 3
  solve_type: Distance
